name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: General stats
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics/general.svg
          base: 'header, activity, community, repositories, metadata'
          plugin_lines: yes
          plugin_lines_sections: base
          config_timezone: Asia/Kolkata

      - name: Top languages
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics/languages.svg
          base: ''
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%

      - name: Achievements
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics/achievements.svg
          base: ''
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

      - name: Coding habits
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics/habits.svg
          base: ''
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          config_timezone: Asia/Kolkata

      - name: Isometric contribution calendar
        uses: lowlighter/metrics@latest
        continue-on-error: true
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics/isocalendar.svg
          base: ''
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Kolkata
